version: '3.8'

services:
  ton-emulator:
    container_name: ton-emulator
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/output
    command: ["cp", "build/emulator/libemulator.so", "./output"]


volumes:
  output: